name: Sync to Gitee
on:
  push:
    branches: []          # 触发分支（所有分支）
  workflow_dispatch:      # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        with:
          # 源仓库（GitHub）
          source-repo: "git@github.com:${{ github.repository }}.git"
          # 目标仓库（Gitee）
          destination-repo: "git@gitee.com:tazy/tazy-tools.git"
